/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg decimal
);

Alter TABLE animals ADD species char(20);

Update animals set species='unspecified';
ROLLBACK;
Update animals  SET species='digimon' WHERE name LIKE '%mon';
Update animals  SET species='pokemon' WHERE species IS NUll;

BEGIN;
DELETE FROM animals; 
ROLLBACK;
Select *from animals;


Delete from animals where date_of_birth > 'Jan 1 2022';
SAVEPOINT save1;
UPDATE animals set weight_kg= weight_kg * -1 where weight_kg < 0;
ROLLBACK;
UPDATE animals set weight_kg= weight_kg * -1 where weight_kg < 0;
Commit;

CREATE TABLE owners (
    id int GENERATED BY DEFAULT AS IDENTITY,
    full_name varchar(100),
    age decimal,
    PRIMARY KEY (ID)
);

CREATE TABLE species (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    PRIMARY KEY (id)
);

ALTER TABLE animals ADD PRIMARY KEY (id);
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD COLUMN species_id char REFERENCES species(id);
ALTER TABLE animals ADD COLUMN owner_id INT REFERENCES owners(id);

CREATE TABLE vets (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    age int,
    date_of_graduation date,
    PRIMARY KEY (id)
);
CREATE TABLE specialization(
    species_id INT REFERENCES species(id),
    vet_id INT REFERENCES vets(id)
);
CREATE TABLE visits(
    animal_id INT REFERENCES animals(id),
    vet_id INT REFERENCES vets(id),
    date_of_visit DATE
);


